### ISSUE TITLE
Support for device info in ports

### ISSUE THREAD

**Issue by strycore** [mk-fg/python-pulse-control#15]
Hi,

I'm writing a tool that switches the audio channel when an external display is switched on. Depending on the state of the display, the profile name can change, for example my TV is either HDMI 2 or HDMI 3.

I've figured a way to workaround that but pulsectl seems to be missing that info. When I run `pacmd list-sinks`, I get something like:

```
        [...]
	ports:
		hdmi-output-1: HDMI / DisplayPort 2 (priority 5800, latency offset 0 usec, available: yes)
			properties:
				device.icon_name = "video-display"
				device.product.name = "FullHD TV
```

I would like to access the device.product.name property but it's not exposed by PulsePortInfo, would it be possible to add that? 

Thanks!

**Comment by mk-fg** [comment]
Hi.

I think pacmd cheats there, as `pa_sink_port_info` struct doesn't have proplist:
```
typedef struct pa_sink_port_info {
    const char *name;                   /**< Name of this port */
    const char *description;            /**< Description of this port */
    uint32_t priority;                  /**< The higher this value is, the more useful this port is as a default. */
    int available;                      /**< A flags (see #pa_port_available), indicating availability status of this port. \since 2.0 */
} pa_sink_port_info;
```
pactl doesn't show these properties in its `pactl list sinks` either.

As you probably know, difference between pacmd and pactl is that former doesn't use any structured API but rather connects to pulseaudio cli module instead and runs specified stuff there.
Which is why it can sometimes show/allow more stuff which is not exposed via libpulse introspection api.

There's a quirk which I didn't notice before though: `pa_card_port_info`, while being compatible with sink/source port-info structs, has much more stuff appended, and has "proplist" in particular.

Without looking into how pacmd does its magic, I suspect these properties listed for sink are actually queried or copied from the card's port.
And if that's the case, guess getting this info from "special" PulsePortInfo for cards should be possible at least, but not sure whether it should be auto-copied to sink ports - probably not, need to check what list-sinks dumps though, I guess.

**Comment by mk-fg** [comment]
Internally pulseaudio seem to have only pa_device_port structs, while libpulse api exposes separate sink/source/card port structs, which is probably intentional.

As of e5fedbb / 17.6.0 there're separate PulseCardPortInfo objects which have "proplist" with values you've seen in pacmd, but these are not copied to all PulsePortInfo objects, as that'd require extra calls to fetch card info, and there can potentially be mismatch between ports on these, given how api is structured.

For a script that needs these properties, I'd suggest always using card.port_list instead of sink.port_list, i.e.:
```python
with Pulse('port-test') as pulse:
  sink = pulse.sink_list()[0]
  ports = pulse.card_info(sink.card).port_list
  print(ports)
  # sink.port_set(ports[0])
```

`sink.port_set()` should not care whether it's a PulsePortInfo or PulseCardPortInfo and only use its "name" attribute, which should not cause any issues as long as port lists match between sink/card.
And if they don't, you probably don't want this module to handle such mismatch anyway, and will need to resolve it in the script by either hiding some ports or not displaying info for them.
