### ISSUE TITLE
Unit tests failing in setUpClass

### ISSUE THREAD

**Issue by stickster** [mk-fg/python-pulse-control#26]
Details: https://gist.github.com/stickster/4cc363955b2dd0aedea9d06b9cb7fe8c

I'm running Fedora 28 on x86_64. I cloned the repo and started by running the unittests which failed in setUpClass. I put pulseaudio and python3 versions in the gist linked above. Happy to provide any other output that would help you.

**Comment by mk-fg** [comment]
Just started Fedora-Workstation-Live-x86_64-28-1.1.iso in a kvm, ran pip3 install --user there and seeing exactly same issue, even with pulseaudio 11.1-rebootstrapped.

Running `PA_DEBUG=1 python3 -m unittest pulsectl.tests.all` with module installed, found that pulse starts normally, but then ignores test-instance config that is written to its stdin (as is clear from verbose logging), and instead waits for it on the current terminal, even though "man pulseaudio" still says "-C  Open a command interpreter on STDIN/STDOUT after startup".
Easy fix seem to be using "-F /dev/stdin" instead "-C" for non-interactive but still file-less input, which I've applied in latest 73dd112 commit.
As it seem to be rather harmless tweak, did push it to pypi as well as git master here.

Try to update installed module or git clone and re-run the tests - should work fine now, but please do report/reopen if still doesn't.

A bit weird that it doesn't happen to me on Arch with pulseaudio 12.2, but guess maybe Fedora builds it with readline or some similar console-input lib support, which detects that the process was started in terminal and connects module-cli to it instead of stdin.

Thanks for reporting it!
