### ISSUE TITLE
Wrong unit for timeout of mainloop_prepare

### ISSUE THREAD

**Issue by wedjat** [mk-fg/python-pulse-control#68]
The the parameter `timeout ` is passed to `pa_mainloop_prepare()` in milliseconds instead of micoseconds.
This causes higher CPU load when waiting for an event in case `event_listen()` is called with a timeout parameter.

https://github.com/mk-fg/python-pulse-control/blob/08395ddf0f5d7308e4fe05f6b3cc6fff57ec070a/pulsectl/pulsectl.py#L533

Also see https://freedesktop.org/software/pulseaudio/doxygen/mainloop_8h.html#a217ce134af601c1c6ce77c41c99fc0d2
![image](https://user-images.githubusercontent.com/679984/149829597-25cdc53b-f065-41d0-a045-f216b6e45f0c.png)

**Comment by mk-fg** [comment]
Huh, indeed was a bug, introduced in 4bc5437058045339f6b38cc8582b94b236995ebd where apparently I thought it was ms, even though it says "us" in the signature and microseconds in the headers.
Not sure what was going on there, but definitely looks like a mistake.

Should be fixed in 22.1.0. Thanks for noticing and reporting!
