### ISSUE TITLE
call pulsectl.Pulse() after pygame result "Assertion 'c' failed at pulse/context.c:1083, function pa_context_set_state_callback(). Aborting."

### ISSUE THREAD

**Issue by MrLittleant** [mk-fg/python-pulse-control#83]
```
import multiprocessing
import pulsectl
import pygame

class MP(multiprocessing.Process):
    def run(self):
        pulse = pulsectl.Pulse("my-app")
        sinks = pulse.sink_list()
        for sink in sinks:
            print(f"Sink name: {sink.name}, Volume: {sink.volume}")

class Main:
    def foo(self):
        p1 = MP()
        p1.start()
        p1.join()
        pygame.init()
        p2 = MP()
        p2.start()
        p2.join()

if __name__ == "__main__":
    a = Main()
    a.foo()
```

**Output:**

> pygame 2.6.1 (SDL 2.28.4, Python 3.9.2)
> Hello from the pygame community. https://www.pygame.org/contribute.html
> Sink name: NullSink, Volume: channels=2, volumes=[100% 100%]
> Sink name: alsa_output.platform-bcm2835_audio.analog-stereo, Volume: channels=2, volumes=[100% 100%]
> Sink name: alsa_output.platform-soc_sound.iec958-stereo, Volume: channels=2, volumes=[100% 100%]
> **Assertion 'c' failed at pulse/context.c:1083, function pa_context_set_state_callback(). Aborting.**

**System:**
Python 3.9
pulsectl 24.8.0
pygame 2.6.1
OS: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.15.61-v8+
Architecture: arm64

**Comment by mk-fg** [comment]
I think there are two issues here:

- pa_context_new() doesn't catch when libpulse returns NULL, hence assertion error instead of Exception.
- libpulse does not allow any usage in child processess after you initialize it in the parent one.

First one should be fixed by 776385b commit.
NULL return on error doesn't seem to be documented there, was maybe added at some later point without updating function description.

But the second issue cannot be fixed here, unfortunately.
pa_context_new() and a bunch of other basic functions run pa_detect_fork() check, which permanently ties loaded libpulse usage to the pid (process id) that this call was invoked in. Any usage from a different process (likely a child pid) will result in libpulse returning error on this check.
As far as I can tell, this check sets global variable not tied to a loop or context, so there is no avoiding it by any init/close sequences, and it's likely done for a good enough reason to not bother hacking around it in any other ways (e.g. libpulse patch).

I think best fix for the code is to fork any other processes using libpulse before running pygame.init(), which seem to initialize libpulse as well (in whatever process it's invoked in), and not use libpulse in a transient subprocesses started after that.
If you have to do something related to libpulse from later-started subprocesses, any such activity would have to be delegated to one of these older pre-forked processes with this model.

For I/O-bound activity (where tasks mostly wait on something), you can also use threads instead of processes (but they also have their own list of caveats and difficulties), or asyncio loop with [pulsectl-asyncio](https://pypi.org/project/pulsectl-asyncio/) if pygame supports it too.

Hope it helps, thanks for reporting.
